// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Pilfered, PilferedTableId } from "./tables/Pilfered.sol";
import { Balances, BalancesTableId } from "./tables/Balances.sol";
