// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPilferSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPilferSystem {
  function batman6_PilferSystem_pilfer(bytes32 matchEntity, bytes32 entity) external;
}
