// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITokenMUDSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITokenMUDSystem {
  function transfer(bytes32 token, bytes32 to, uint256 value) external;

  function approve(bytes32 token, bytes32 spender, uint256 value) external;

  function transferFrom(bytes32 token, bytes32 from, bytes32 to, uint256 value) external;
}
